export const COUNTRIES = [
  { code: "BR", flag: "🇧🇷", name: "Brazil" },
  { code: "US", flag: "🇺🇸", name: "United States" },
  { code: "ID", flag: "🇮🇩", name: "Indonesia" },
  { code: "MX", flag: "🇲🇽", name: "Mexico" },
  { code: "PH", flag: "🇵🇭", name: "Philippines" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam" },
  { code: "TH", flag: "🇹🇭", name: "Thailand" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
  { code: "TR", flag: "🇹🇷", name: "Turkey" },
  { code: "SA", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "EG", flag: "🇪🇬", name: "Egypt" },
  { code: "DE", flag: "🇩🇪", name: "Germany" },
  { code: "FR", flag: "🇫🇷", name: "France" },
  { code: "JP", flag: "🇯🇵", name: "Japan" },
  { code: "KR", flag: "🇰🇷", name: "South Korea" },
  { code: "IN", flag: "🇮🇳", name: "India" },
  { code: "RU", flag: "🇷🇺", name: "Russia" },
  { code: "IT", flag: "🇮🇹", name: "Italy" },
  { code: "ES", flag: "🇪🇸", name: "Spain" },
  { code: "AR", flag: "🇦🇷", name: "Argentina" },
  { code: "CO", flag: "🇨🇴", name: "Colombia" },
  { code: "PL", flag: "🇵🇱", name: "Poland" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia" },
  { code: "AU", flag: "🇦🇺", name: "Australia" },
  { code: "CA", flag: "🇨🇦", name: "Canada" },
  { code: "NL", flag: "🇳🇱", name: "Netherlands" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan" },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh" },
  { code: "NG", flag: "🇳🇬", name: "Nigeria" },
  { code: "UA", flag: "🇺🇦", name: "Ukraine" },
  { code: "RO", flag: "🇷🇴", name: "Romania" },
  { code: "IQ", flag: "🇮🇶", name: "Iraq" },
  { code: "MA", flag: "🇲🇦", name: "Morocco" },
  { code: "PE", flag: "🇵🇪", name: "Peru" },
  { code: "CL", flag: "🇨🇱", name: "Chile" },
  { code: "TW", flag: "🇹🇼", name: "Taiwan" },
  { code: "IL", flag: "🇮🇱", name: "Israel" },
  { code: "SE", flag: "🇸🇪", name: "Sweden" },
  { code: "BE", flag: "🇧🇪", name: "Belgium" },
  { code: "CZ", flag: "🇨🇿", name: "Czechia" },
  { code: "PT", flag: "🇵🇹", name: "Portugal" },
  { code: "AT", flag: "🇦🇹", name: "Austria" },
  { code: "CH", flag: "🇨🇭", name: "Switzerland" },
  { code: "GR", flag: "🇬🇷", name: "Greece" },
  { code: "HU", flag: "🇭🇺", name: "Hungary" },
  { code: "DZ", flag: "🇩🇿", name: "Algeria" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "AE", flag: "🇦🇪", name: "United Arab Emirates" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa" },
];
